'use client';

import React, { useState } from 'react';
import { BugReport as BugReportType } from '@/lib/schemas';
import SeverityBadge from './SeverityBadge';
import { Copy, Check, Download, AlertTriangle, Lightbulb, FileText, CheckCircle2 } from 'lucide-react';

interface BugReportProps {
  report: BugReportType;
}

export default function BugReport({ report }: BugReportProps) {
  const [copied, setCopied] = useState(false);

  const getMarkdownReport = () => {
    return `## Bug Report: ${report.title}
    
**Status**: ${report.status.toUpperCase()}
**Severity**: ${report.severity.toUpperCase()}
**Confidence**: ${report.confidence.toUpperCase()}

### Expected Behavior
${report.expectedBehavior}

### Actual Behavior
${report.actualBehavior}

### Failed Step
${report.failedStep || 'N/A'}

### Reproduction Steps
${report.reproductionSteps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

### Observed Errors
${report.observedErrors.map(err => `- ${err}`).join('\n')}

### Hypothesis on Possible Cause
${report.possibleCause}

### Suggested Fix
${report.suggestedFix}

---
*Report generated by ShipCheck AI Bug Analyzer.*`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `shipcheck-report-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const passed = report.status === 'passed';

  if (passed) {
    return (
      <div className="bg-bg-card border border-emerald-500/25 rounded-2xl p-6 shadow-sm space-y-4">
        <div className="flex items-center gap-3">
          <CheckCircle2 size={32} className="text-emerald-500" />
          <div>
            <h2 className="text-xl font-bold text-text-primary font-serif-anthropic">{report.title}</h2>
            <p className="text-xs text-text-secondary">All tests executed and verified successfully.</p>
          </div>
        </div>
        <div className="p-4 bg-emerald-500/5 border border-emerald-500/10 rounded-xl space-y-2 text-sm text-text-primary min-w-0">
          <p className="break-words"><strong>Expected:</strong> {report.expectedBehavior}</p>
          <p className="break-words"><strong>Observed:</strong> {report.actualBehavior}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-bg-card border border-border-subtle rounded-2xl overflow-hidden shadow-sm">
      {/* Header Banner */}
      <div className="p-6 bg-bg-app/40 border-b border-border-subtle flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-3 flex-wrap">
            <SeverityBadge severity={report.severity} />
            <span className="text-xs text-text-secondary font-mono">
              Confidence: {report.confidence}
            </span>
          </div>
          <h2 className="text-xl font-bold text-text-primary font-serif-anthropic mt-2">{report.title}</h2>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-text-primary hover:text-accent-primary bg-bg-app border border-border-subtle rounded-lg active:scale-95 transition cursor-pointer shadow-sm"
          >
            {copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
            <span>{copied ? 'Copied' : 'Copy MD'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-text-primary hover:text-accent-primary bg-bg-app border border-border-subtle rounded-lg active:scale-95 transition cursor-pointer shadow-sm"
          >
            <Download size={14} />
            <span>JSON</span>
          </button>
        </div>
      </div>

      <div className="p-6 space-y-6">
        {/* Core Description Grid */}
        <div className="grid md:grid-cols-2 gap-6">
          <div className="space-y-2 p-4 bg-bg-app border border-border-subtle rounded-xl">
            <h4 className="text-xs font-semibold text-text-secondary uppercase tracking-wider">
              Expected Behavior
            </h4>
            <p className="text-sm text-text-primary leading-relaxed break-words">{report.expectedBehavior}</p>
          </div>
          <div className="space-y-2 p-4 bg-bg-app border border-border-subtle rounded-xl min-w-0">
            <h4 className="text-xs font-semibold text-text-secondary uppercase tracking-wider">
              Actual Behavior
            </h4>
            <p className="text-sm text-red-600 dark:text-red-400 leading-relaxed break-words">{report.actualBehavior}</p>
          </div>
        </div>

        {/* Failed Step Display */}
        {report.failedStep && (
          <div className="flex items-center gap-2 p-3 bg-red-500/5 border border-red-500/20 text-red-500 rounded-xl text-xs">
            <AlertTriangle size={14} />
            <span>Failed Step: <strong className="font-semibold">{report.failedStep}</strong></span>
          </div>
        )}

        {/* Reproduction Steps */}
        <div className="space-y-3">
          <h4 className="text-xs font-semibold text-text-secondary uppercase tracking-wider flex items-center gap-1.5">
            <FileText size={14} /> Reproduction Steps
          </h4>
          <ol className="divide-y divide-border-subtle border border-border-subtle rounded-xl bg-bg-app/40 overflow-hidden text-sm">
            {report.reproductionSteps.map((step, index) => (
              <li key={index} className="p-3.5 flex items-start gap-3">
                <span className="w-5 h-5 flex items-center justify-center rounded-full bg-bg-card border border-border-subtle text-[10px] text-text-secondary font-mono mt-0.5">
                  {index + 1}
                </span>
                <span className="text-text-primary">{step}</span>
              </li>
            ))}
          </ol>
        </div>

        {/* Hypothesis on Possible Cause */}
        <div className="p-4 bg-bg-app border border-border-subtle rounded-xl space-y-2 relative overflow-hidden">
          <div className="flex items-center gap-2 text-accent-primary text-xs font-semibold uppercase tracking-wider">
            <AlertTriangle size={14} />
            <span>Root Cause Hypothesis</span>
          </div>
          <p className="text-sm text-text-primary leading-relaxed">
            {report.possibleCause}
          </p>
          {/* Warn about hypothesis nature */}
          <div className="text-[10px] text-text-secondary/50 pt-1 border-t border-border-subtle flex items-center gap-1">
            <span>Note: This is an AI-generated analysis. Confirm actual cause in code.</span>
          </div>
        </div>

        {/* Suggested Fix */}
        <div className="p-4 bg-accent-glow border border-accent-primary/20 rounded-xl space-y-2">
          <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 text-xs font-semibold uppercase tracking-wider">
            <Lightbulb size={14} />
            <span>Suggested Action Plan</span>
          </div>
          <p className="text-sm text-text-primary leading-relaxed">
            {report.suggestedFix}
          </p>
        </div>

        {/* Warnings Alert Box */}
        {report.warnings && report.warnings.length > 0 && (
          <div className="p-4 bg-amber-550/5 border border-amber-500/20 rounded-xl space-y-1">
            <h5 className="text-xs font-bold text-amber-600 dark:text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
              <AlertTriangle size={14} /> Warnings & Assumptions
            </h5>
            <ul className="list-disc pl-5 text-xs text-amber-700 dark:text-amber-300/80 space-y-1">
              {report.warnings.map((warning, index) => (
                <li key={index}>{warning}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
}
