import { z } from 'zod';

// Supported browser actions
export const ActionTypeSchema = z.enum(['navigate', 'click', 'fill', 'verify']);
export type ActionType = z.infer<typeof ActionTypeSchema>;

// Individual step generated by the AI Planner
export const TestStepSchema = z.object({
  id: z.string(),
  action: ActionTypeSchema,
  target: z.string().optional().describe('URL path for navigate, text/selector for click or verify'),
  field: z.string().optional().describe('Field label, placeholder, or selector for fill'),
  value: z.string().optional().describe('Value to fill into the input field'),
  description: z.string().describe('Human-readable description of what this step does'),
});
export type TestStep = z.infer<typeof TestStepSchema>;

// Complete test plan generated by the AI Planner
export const TestPlanSchema = z.object({
  goal: z.string().describe('The overall objective of the test'),
  steps: z.array(TestStepSchema).describe('The sequence of browser steps to execute'),
});
export type TestPlan = z.infer<typeof TestPlanSchema>;

// Execution result of an individual step
export const StepResultSchema = z.object({
  stepId: z.string(),
  status: z.enum(['pending', 'running', 'passed', 'failed', 'skipped', 'timed_out']),
  durationMs: z.number().optional(),
  error: z.string().optional(),
  screenshotPath: z.string().optional(),
  url: z.string().optional(),
});
export type StepResult = z.infer<typeof StepResultSchema>;

// Captured console errors
export const ConsoleErrorSchema = z.object({
  type: z.string(),
  text: z.string(),
  timestamp: z.string(),
});
export type ConsoleError = z.infer<typeof ConsoleErrorSchema>;

// Captured general evidence
export const EvidenceSchema = z.object({
  id: z.string(),
  stepId: z.string().optional(),
  type: z.enum(['screenshot', 'console_error', 'page_error', 'url', 'text']),
  value: z.string(),
  timestamp: z.string(),
});
export type Evidence = z.infer<typeof EvidenceSchema>;

// Zod schema for structured bug report generated by AI Analyzer
export const BugReportSchema = z.object({
  status: z.enum(['passed', 'failed']),
  title: z.string().describe('Short, descriptive title of the bug or test status'),
  severity: z.enum(['critical', 'high', 'medium', 'low']).describe('Calculated based on user impact'),
  failedStep: z.string().nullable().describe('The exact description of the step that failed, if any'),
  expectedBehavior: z.string().describe('What should have occurred in the happy path'),
  actualBehavior: z.string().describe('What actually occurred based on the evidence'),
  reproductionSteps: z.array(z.string()).describe('Step-by-step instructions to reproduce the issue'),
  observedErrors: z.array(z.string()).describe('List of console errors, server responses, or network failures observed'),
  possibleCause: z.string().describe('Hypothesized technical cause of the failure'),
  suggestedFix: z.string().describe('Actionable developer recommendation to resolve the issue'),
  confidence: z.enum(['high', 'medium', 'low']).describe('Analyzer confidence in the diagnosis'),
  warnings: z.array(z.string()).describe('Caveats, limitations of evidence, or assumptions made'),
});
export type BugReport = z.infer<typeof BugReportSchema>;

// Representation of a full Test Run in the system
export const TestRunSchema = z.object({
  id: z.string(),
  url: z.string(),
  task: z.string(),
  expectedResult: z.string().optional(),
  status: z.enum(['created', 'planning', 'planned', 'running', 'passed', 'failed', 'timed_out', 'cancelled', 'error']),
  progress: z.number(), // 0 to 100
  planId: z.string().optional(),
  plan: TestPlanSchema.optional(),
  steps: z.array(StepResultSchema),
  evidence: z.array(EvidenceSchema),
  consoleErrors: z.array(ConsoleErrorSchema),
  bugReport: BugReportSchema.optional(),
  latestScreenshotPath: z.string().optional(),
  errorMessage: z.string().optional(),
  createdAt: z.string(),
  finishedAt: z.string().optional(),
});
export type TestRun = z.infer<typeof TestRunSchema>;
